Add more type hints
faif/python-patterns pull request #397
Opened 2022-07-27 03:24 UTC by alexkahan

Add type hints to multiple design pattern examples

Related to https://github.com/faif/python-patterns/issues/373

2022-07-28 21:46 UTC, JKearnsl requested changes
Using the "-> None" hint in __init__ is meaningless, since __init__ always returns None and we can't use that anywhere.

The same goes for "-> str" in __repr__ and __str__ as we already deliberately know that these methods always return a string -> this is pointless

2022-07-28 21:46 UTC, JKearnsl commented on patterns/behavioral/publish_subscribe.py
> +    def __init__(self) -> None:
pointless

2022-07-28 21:46 UTC, JKearnsl commented on patterns/behavioral/publish_subscribe.py
> +    def __init__(self, msg_center: Provider) -> None:
pointless

2022-07-28 21:46 UTC, JKearnsl commented on patterns/behavioral/publish_subscribe.py
> +    def __init__(self, name: str, msg_center: Provider) -> None:
pointless

2022-07-28 21:46 UTC, JKearnsl commented on patterns/behavioral/state.py
> +    def __init__(self, radio: Radio) -> None:
pointless

2022-07-28 21:46 UTC, JKearnsl commented on patterns/behavioral/state.py
> +    def __init__(self, radio: Radio) -> None:
pointless

2022-07-28 21:46 UTC, JKearnsl commented on patterns/behavioral/state.py
> +    def __init__(self) -> None:
pointless

2022-07-28 21:46 UTC, JKearnsl commented on patterns/creational/borg.py
> +    def __init__(self) -> None:
pointless

2022-07-28 21:46 UTC, JKearnsl commented on patterns/creational/borg.py
> +    def __init__(self, state: str = None) -> None:
pointless

2022-07-28 21:46 UTC, JKearnsl commented on patterns/creational/borg.py
> +    def __str__(self) -> str:
pointless

2022-07-28 21:46 UTC, JKearnsl commented on patterns/creational/builder.py
> +    def __init__(self) -> None:
pointless

2022-07-28 21:46 UTC, JKearnsl commented on patterns/creational/builder.py
> +    def __repr__(self) -> str:
pointless

2022-07-28 21:46 UTC, JKearnsl commented on patterns/creational/builder.py
> +    def __repr__(self) -> str:
pointless

2022-07-28 21:46 UTC, JKearnsl commented on patterns/fundamental/delegation_pattern.py
> +    def __init__(self, delegate: Delegate) -> None:
pointless

2022-07-28 21:46 UTC, JKearnsl commented on patterns/fundamental/delegation_pattern.py
> +    def __init__(self) -> None:
pointless

2022-07-28 21:46 UTC, JKearnsl commented on patterns/other/blackboard.py
> +    def __init__(self) -> None:
pointless "-> None" in __init__()

2022-07-28 21:46 UTC, JKearnsl commented on patterns/other/blackboard.py
> +    def __init__(self, blackboard: Blackboard) -> None:
pointless "-> None" in init()

2022-07-28 21:46 UTC, JKearnsl commented on patterns/other/blackboard.py
> +    def __init__(self, blackboard: Blackboard) -> None:
pointless "-> None" in init()

2022-07-28 21:46 UTC, JKearnsl commented on patterns/structural/decorator.py
> +    def __init__(self, text: str) -> None:
pointless "-> None" in init()

2022-07-28 21:46 UTC, JKearnsl commented on patterns/structural/decorator.py
> +    def __init__(self, wrapped: TextTag) -> None:
pointless "-> None" in init()

2022-07-28 21:46 UTC, JKearnsl commented on patterns/structural/decorator.py
> +    def __init__(self, wrapped: TextTag) -> None:
pointless "-> None" in init()

2022-07-28 21:46 UTC, JKearnsl commented on patterns/structural/front_controller.py
> +    def __init__(self) -> None:
pointless "-> None" in init()

2022-07-28 21:46 UTC, JKearnsl commented on patterns/structural/front_controller.py
> +    def __init__(self) -> None:
pointless "-> None" in init()

2022-07-29 17:43 UTC, faif commented
We have already discussed about the `None` hints in another issue, and agreed to keep them, since this seems to be the convention. I'm also not a big fan of them, but I won't go against the syntax conventions of type hints.

2022-07-29 18:32 UTC, JKearnsl commented
> We have already discussed about the `None` hints in another issue, and agreed to keep them, since this seems to be the convention. I'm also not a big fan of them, but I won't go against the syntax conventions of type hints.

OK. 
I'm just going from the logical meaning of the clues, not from mindless beliefs.

2022-08-07 15:18 UTC, faif commented
Hi @alexkahan, can you look into the linter issues? Thanks.

2022-08-07 21:18 UTC, alexkahan commented
> Hi @alexkahan, can you look into the linter issues? Thanks.

Sorry for the delay. Should be fixed, seemed like it was having an issue with the List type hint

2022-08-07 21:51 UTC, JKearnsl approved these changes

2022-08-08 19:13 UTC, merged